services:    
    
    app_test:
      image: ghcr.io/why-not-try-calmer/feedo-test:latest
      profiles: [test]
      depends_on: [mongo_test, redis]
      container_name: feedfarer-test
      restart: "no"
      build: 
        context: .
        dockerfile: Dockerfile-test
      environment:
        - ALERT_CHATID
        - BASE_URL
        - MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_ROOT_USERNAME
        - TELEGRAM_TOKEN
        - TEST=1
        - WEBHOOK_URL

    app:
      image: ghcr.io/why-not-try-calmer/feedo:latest
      depends_on: [mongo, redis]
      restart: "on-failure"
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - ALERT_CHATID
        - BASE_URL
        - MONGO_INITDB_ROOT_PASSWORD 
        - MONGO_INITDB_ROOT_USERNAME
        - TELEGRAM_TOKEN
        - WEBHOOK_URL
      volumes:
        - ./static:/var/www/feedfarer-webui
    
    mongo:
      image: mongo:5.0 # `auth` doesn't work with 6.0 and beyond!
      restart: "on-failure"
      command: --wiredTigerCacheSizeGB 0.25 # trying to fight RAM exhaustion
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - mongo-data:/data/db
        - ./scripts/mongo-startup.js:/scripts/mongo-startup.js:ro
      ports:
        - "27017:27017"
       
    mongo_test:
      profiles: [test]
      image: mongo:5.0 # `auth` doesn't work with 6.0 and beyond!
      restart: "on-failure"
      command: --wiredTigerCacheSizeGB 0.25 # trying to fight RAM exhaustion
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - mongo-data:/data/db
        - ./scripts/mongo-startup.js:/scripts/mongo-startup.js:ro
      ports:
        - "27017:27017"

    nginx:
      depends_on: [app]
      image: nginx:latest
      restart: "on-failure"
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf:ro"
        - "/certs/etc/live/feedo.cloudns.ph/fullchain.pem:/etc/nginx/cert.pem:ro"
        - "/certs/etc/live/feedo.cloudns.ph/privkey.pem:/etc/nginx/private.key:ro"
      ports:
        - "80:80"
        - "443:443"
  
    redis:
      image: redis:latest
      restart: "on-failure"
      command: redis-server --maxmemory 250mb --maxmemory-policy volatile-lfu
      volumes:
        - redis-data:/data/redis-store

volumes:
  mongo-data:
  redis-data:
