version: "3"
services:
    feedfarer-test:
      container_name: feedfarer-test
      depends_on: [redis]
      restart: "no"
      build: 
        context: .
        dockerfile: Dockerfile-test
      command: stack test --fast
      environment:
        - API_KEY
        - TELEGRAM_TOKEN
        - BASE_URL
        - ALERT_CHATID
        - WEBHOOK_URL
        - MONGO_CONN_STRING
    redis:
        image: redis:latest
        expose: [6379]
        restart: unless-stopped
        command: redis-server --maxmemory 200mb --maxmemory-policy volatile-lfu
        volumes:
          - /data/redis-store