services:    
    
    test:
      image: ghcr.io/feedo-test:latest
      profiles: [test]
      depends_on: [mongo, redis]
      container_name: feedfarer-test
      restart: "no"
      build: 
        context: .
        dockerfile: Dockerfile-test
      environment:
        - API_KEY
        - TELEGRAM_TOKEN
        - BASE_URL
        - ALERT_CHATID
        - WEBHOOK_URL
        - MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_ROOT_USERNAME
        - TEST=1

    app:
      depends_on: [mongo, redis]
      image: ghcr.io/why-not-try-calmer/feedo:latest
      restart: "on-failure"
      build:
        context: .
        dockerfile: Dockerfile
      command: ./feedfarer-exe
      environment:
        API_KEY: ${API_KEY}
        TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
        BASE_URL: ${BASE_URL}
        ALERT_CHATID: ${ALERT_CHATID}
        WEBHOOK_URL: ${WEBHOOK_URL}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        PORT: 8000
    
    mongo:
      image: mongo:5.0 # `auth` doesn't work with 6.0 and beyond!
      restart: "on-failure"
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
      volumes:
       - mongo-data:/data/db
       
    nginx:
      depends_on: [app]
      image: nginx:latest
      restart: "on-failure"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./private.key:/etc/nginx/private.key:ro
        - ./cert.pem:/etc/nginx/cert.pem:ro
      ports:
        - "80:80"
        - "443:443"
  
    redis:
      image: redis:latest
      restart: "on-failure"
      command: redis-server --maxmemory 250mb --maxmemory-policy volatile-lfu
      volumes:
        - redis-data:/data/redis-store

volumes:
  mongo-data:
  redis-data:
