name: feedfarer
version: 1.3
github: "githubuser/feedfarer"
license: BSD3
author: "Adrien Glauser"
maintainer: "mrnycticorax@gmail.com"
copyright: "2024 Adrien Glauser"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/githubuser/feedfarer#readme>

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - StrictData
  - BangPatterns

dependencies:
  - base >= 4.7 && < 5
  - async
  - aeson
  - blaze-html
  - blaze-markup
  - bytestring
  - containers
  - cryptonite
  - directory
  - hedis
  - http-client
  - hspec
  - mongoDB
  - mtl
  - req
  - retry
  - servant-blaze
  - servant-server
  - text
  - time
  - unordered-containers
  - uri-encode
  - wai
  - warp
  - warp-tls
  - xml-conduit

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  feedfarer-exe:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    when:
      - condition: flag(static)
        ghc-options:
          - -static
        ld-options:
          - -static
          - -pthread
        cc-options:
          - -static
    dependencies:
      - feedfarer

  feedfarer-worker-exe:
    main: Main.hs
    source-dirs: worker
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    when:
      - condition: flag(static)
        ghc-options:
          - -static
        ld-options:
          - -static
          - -pthread
        cc-options:
          - -static
    dependencies:
      - feedfarer

tests:
  feedfarer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - feedfarer

flags:
  static:
    description: Enable static linking
    manual: true
    default: false
