name:                feedfarer
version:             1.1
github:              "why-not-try-calmer/feedfarer"
license:             BSD3
author:              "Adrien Glauser"
maintainer:          "adrien.glauser@gmail.com"
copyright:           "2021 Adrien Glauser"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/why-not-try-calmer/feedfarer2#readme>

default-extensions:
- LambdaCase
- OverloadedStrings
- StrictData
- BangPatterns

dependencies:
- base >= 4.7 && < 5
- xml-conduit
- req
- text
- bytestring
- unordered-containers
- containers
- mtl
- time
- async
- aeson
- servant-server
- wai
- warp
- mongoDB
- hedis
- servant-blaze
- blaze-markup
- blaze-html
- uri-encode
- cryptonite
- hspec

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  feedfarer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - feedfarer

tests:
  feedfarer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - feedfarer
