version: "3"
services:
    feedfarer:
        depends_on: [redis]
        restart: "no"
        build: .
        command: stack test
        ports: [80:80]
        secretsironment:
         - TELEGRAM_TOKEN=${{secrets.TELEGRAM_TOKEN}}}
         - BASE_URL=${secrets.BASE_URL}
         - ALERT_CHATID=${secrets.ALERT_CHATID}
         - WEBHOOK_URL=${secrets.WEBHOOK_URL}
         - MONGO_CONN_STRING=${secrets.MONGO_CONN_STRING}
    redis:
        image: redis:latest
        ports: [6379:6379]
        restart: unless-stopped
        volumes:
          - /data/redis-store
