version: "3"
services:
    feedfarer:
        depends_on: [redis]
        restart: "no"
        build: .
        command: stack test
        ports: [80:80]
        environment:
         - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
         - BASE_URL=${BASE_URL}
         - ALERT_CHATID=${ALERT_CHATID}
         - WEBHOOK_URL=${WEBHOOK_URL}
         - MONGO_CONN_STRING=${MONGO_CONN_STRING}
    redis:
        image: redis:latest
        ports: [6379:6379]
        restart: unless-stopped
        volumes:
          - /data/redis-store
