version: "3"
services:
    feedfarer-test:
      container_name: feedfarer-test
      depends_on: [redis]
      restart: "no"
      build: .
      command: stack test
      ports: [80:80]
      environment:
        - TELEGRAM_TOKEN
        - BASE_URL
        - ALERT_CHATID
        - WEBHOOK_URL
        - MONGO_CONN_STRING
    redis:
        image: redis:latest
        expose: [6379]
        restart: unless-stopped
        volumes:
          - /data/redis-store