# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - feedfarer-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://adrienazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8a4fc4d7e1234904ab5d3cff2891db4c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4c37abdea9c544b4b25daa03ee0bb6b4 }}

    - name: Build and Test
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        tags: feedfarer
      run: |
        docker run --rm feedfarer stack test

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: adrienazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8a4fc4d7e1234904ab5d3cff2891db4c }}/feedfarer-master:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'feedfarer-webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_757101bf97ec46d6a76b5017189f6a8c }}
        images: 'adrienazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8a4fc4d7e1234904ab5d3cff2891db4c }}/feedfarer-master:${{ github.sha }}'