name: Push Then Deploy

on:
  workflow_run:
    workflows: ["Build Then Store"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${ github.ref }
  cancel-in-progress: true

jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Connect And Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd /opt/app
            docker-compose down --remove-orphans
            docker-compose pull   
            docker-compose up -d
