name: Push Then Deploy

on:
  workflow_run:
    workflows: ["Build Then Store"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Connect to server
        run: |
          bash -c "ssh -i ${{ secrets.PROD }} && ls -a"
