name: Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${ github.ref }
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build & run tests
        env:
          api_key: ${{ secrets.API_KEY }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          base_url: ${{ secrets.BASE_URL }}
          alert_chat_id: ${{ secrets.ALERT_CHATID }}
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          mongo_user: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          mongo_password: $ {{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
        run: |
          API_KEY=$api_key \
          TELEGRAM_TOKEN=$telegram_token \
          BASE_URL=$base_url \
          ALERT_CHATID=$alert_chat_id \
          WEBHOOK_URL=$webhook_url \
          MONGO_INITDB_ROOT_USERNAME=$mongo_user \
          MONGO_INITDB_ROOT_PASSWORD=$mongo_password \
          docker compose run test
