name: GitHub Test suite

on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build & run tests
      env:
        tg: ${{ secrets.TELEGRAM_TOKEN }}
        bu: ${{ secrets.BASE_URL }}
        acid: ${{ secrets.ALERT_CHATID }}
        wh: ${{ secrets.WEBHOOK_URL }}
        mon: ${{ secrets.MONGO_CONN_STRING }}
      run: TELEGRAM_TOKEN=$tg BASE_URL=$bu ALERT_CHATID=$acid WEBHOOK_URL=$wh MONGO_CONN_STRING=$mon docker-compose -f test-build.yml up
