name: Test suite

on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  TEST_TAG: user/myapp:test

jobs:
  build:
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  
    
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.TEST_TAG }}
        file: ./Dockerfile
      
    - name: Test build
      run: |
        docker run --rm ${{ env.TEST_TAG }} stack test